sudo: true

group: deprecated-2017Q3

language: cpp

services:
        - docker

before_install:
        - sudo apt -qq update
        - sudo apt install libegl1-mesa-dev libgles2-mesa-dev
        - sudo apt install libsdl2-dev libsdl2-ttf-dev
        - sudo apt install libsdl2-image-dev libsdl2-mixer-dev
        - docker pull codeclimate/codeclimate:latest

script:
        - make -v      

after_script:
        - ./analyze_code.sh

after_success:
        - make
