sudo: required

dist: trusty

group: deprecated-2017Q3

language: cpp

compiler: g++

install: export CXX="g++-5"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

services:
        - docker

before_install:
        - sudo apt-get -qq update
        - sudo apt-get install libegl1-mesa-dev libgles2-mesa-dev
        - sudo apt-get install libsdl2-dev libsdl2-ttf-dev
        - sudo apt-get install libsdl2-image-dev libsdl2-mixer-dev
        - docker pull codeclimate/codeclimate:latest

script:
        - make -v      
        - make
        - make -d

after_script:
        - ./analyze_code.sh
